config/routes.rb
RailsApp::Application.routes.draw do
  resources :articles

  resources :records
  match '/news', :to => 'news#index'
  match '/admin', :to => 'admin#index'  
  match '/enquiry',   :to => 'pages#enquiry'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/survey',   :to => 'pages#survey'

  root :to => 'pages#home'

  get "pages/home"

  get "pages/enquiry"

  get "pages/contact"

  get "pages/about"

  get "pages/survey"

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # GET /records
  # GET /records.json
  def index
    @records = Record.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Record.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(params[:record])

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, :notice => 'Record was successfully created.' }
        format.json { render :json => @record, :status => :created, :location => @record }
      else
        format.html { render :action => "new" }
        format.json { render :json => @record.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record, :notice => 'Record was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @record.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :ok }
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :event %><br />
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :date_seen %><br />
    <%= f.date_select :date_seen %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.radio_button :gender, "male" %> Male
    <%= f.radio_button :gender, "female" %> Female
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Event</th>
    <th>Date seen</th>
    <th>Gender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @records.each do |record| %>
  <tr>
    <td><%= record.name %></td>
    <td><%= record.email %></td>
    <td><%= record.event %></td>
    <td><%= record.date_seen %></td>
    <td><%= record.gender %></td>
    <td><%= link_to 'Show', record %></td>
    <td><%= link_to 'Edit', edit_record_path(record) %></td>
    <td><%= button_to 'Destroy', record, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>Submit Your Records</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @record.name %>
</p>

<p>
  <b>Email:</b>
  <%= @record.email %>
</p>

<p>
  <b>Event:</b>
  <%= @record.event %>
</p>

<p>
  <b>Date seen:</b>
  <%= @record.date_seen %>
</p>

<p>
  <b>Gender:</b>
  <%= @record.gender %>
</p>


<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>