config/routes.rb
RailsApp::Application.routes.draw do
  resources :articles

  resources :records
  match '/news', :to => 'news#index'
  match '/admin', :to => 'admin#index'  
  match '/enquiry',   :to => 'pages#enquiry'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/survey',   :to => 'pages#survey'

  root :to => 'pages#home'

  get "pages/home"

  get "pages/enquiry"

  get "pages/contact"

  get "pages/about"

  get "pages/survey"

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.surreywildlifetrust.org/sbic/">Official website: Surrey Biodiversity Information Centre</a></li>
    </ul>
  </nav>

<span id="bottomsmall" style="color:brown;"><b>
The Surrey Wildlife Trust Ltd is a company limited by guarantee, Registered in England No: 645176.
<br>
President: Dr. David Bellamy OBE. VAT No: 791.3799.78.
<br>
Registered Charity No: 208123. Charities Aid Foundation "Give As You Earn." Registration No: 005805.<b>
</span>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("tag.jpg", :alt => "Sample App", :class => "round") %>
   <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "News", news_path %></li>
            <li><%= link_to "Enquiry", enquiry_path %></li>
            <li><%= link_to "Submit", new_record_path %></li>
            <li><%= link_to "Survey", survey_path %></li>
          </ul>
     </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>